name: print secret
on: push
jobs:
  print-secret-job:
    runs-on: ubuntu-latest
    env:
      MY_ENV_VRA: "dit is een environment variabele"
    steps:
      - name: print secret
        run: echo "my secret is ${{ secrets.MY_SECRET }}"
      - name: print env var
        run: echo "env var is $MY_ENV_VAR"
